{% set name = "elyra" %}
{% set version = "2.0.0" %}
{% set sha256 = "6c862990620c9c5d6d0fbc991d3b4cc7e38548eb73bef04350840f709cf87558" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - elyra-metadata=elyra.metadata.metadata_app:MetadataApp.main

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - autopep8
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.0
    - jsonschema >=3.2.0
    - jupyter_core >=4.0,<5.0
    - jupyter_client >=6.1.7
    - jupyterlab >=3.0.0
    - jupyterlab-git ==0.30.0b1
    - jupyterlab-lsp >=3.0.0
    - jupyter-resource-usage >=0.5.1
    - kfp ==1.1.2
    - kfp-tekton ==0.5.0
    - kfp-notebook ~=0.18.0
    - minio >=5.0.7,<7.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1,<6.0
    - nbdime >=3.0.0.b1
    - papermill >=2.1.3
    - python >=3.6
    - python-language-server[all] >=0.36.2
    - requests >=2.9.1,<3.0
    - rfc3986-validator >=0.1.1
    - traitlets >=4.3.2
    - urllib3 >=1.24.2
    - websocket-client

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  dev_url: https://github.com/elyra-ai/elyra
  doc_url: https://elyra.readthedocs.io/en/latest
  doc_source_url: https://github.com/elyra-ai/elyra/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: Elyra, a set of AI-centric extensions for JupyterLab Notebooks.
  description: >
    Elyra currently includes: Notebook Pipelines visual editor Ability to run a notebook as a batch job Hybrid runtime support Python script execution capabilities within the editor Reusable Code Snippets (Experimental) Notebook versioning based on git integration Notebook navigation using auto-generated Table of Contents
    Reusable configuration for runtimes

extra:
  recipe-maintainers:
    - akchinSTC
    - kevin-bates
    - lresende
