{% set name = "elyra" %}
{% set version = "3.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-{{ version }}.tar.gz
  sha256: c7da7ed4c810fcac7e7834083c1ce3164ba22b56616c191fb91fa9a392c05ecb

build:
  number: 0
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
    - elyra-pipeline = elyra.cli.pipeline_app:pipeline
    - jupyter-elyra = elyra.elyra_app:launch_instance
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - autopep8 >=1.5.0,<1.5.6
    - black <=21.12b0
    - click >=7.1.1,<8
    - colorama
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.1
    - jsonschema >=3.2.0
    - jupyter-resource-usage >=0.5.1
    - jupyter_client >=6.1.7
    - jupyter_core >=4.0,<5.0
    - jupyter_server >=1.7.0
    - jupyterlab >=3.0.17
    - jupyterlab-git ~=0.32.0
    - jupyterlab-lsp >=3.8.0
    - jupyter-resource-usage >=0.5.1
    - kfp >=1.7.0,<2.0,!=1.7.2
    - kfp-tekton ~=1.0.1
    - minio >=7.0.0,<8.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1
    - nbdime ~=3.1
    - nbformat >=5.1.2
    - networkx >=2.5.1
    - papermill >=2.1.3
    - pygithub
    - python >=3.7
    - python-lsp-server[all] >=1.1.0
    - pyyaml >=5.3.1,<6.0
    - requests >=2.25.1,<3.0
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - urllib3 >=1.26.5
    - watchdog >=2.1.3
    - websocket-client
    - yaspin

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  dev_url: https://github.com/elyra-ai/elyra
  doc_url: https://elyra.readthedocs.io/en/latest
  doc_source_url: https://github.com/elyra-ai/elyra/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: Elyra, a set of AI-centric extensions for JupyterLab Notebooks.
  description: >
    Elyra currently includes: Notebook Pipelines visual editor Ability to run a notebook as a batch job Hybrid runtime support Python script execution capabilities within the editor Reusable Code Snippets (Experimental) Notebook versioning based on git integration Notebook navigation using auto-generated Table of Contents
    Reusable configuration for runtimes

extra:
  recipe-maintainers:
    - akchinSTC
    - kevin-bates
    - lresende
