{% set name = "elyra" %}
{% set version = "1.5.2" %}
{% set sha256 = "2cd2bb22a8a8b565801031c1698196e535753a282bcfd4f1f92560a7837e3269" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - elyra-metadata=elyra.metadata.metadata_app:MetadataApp.main

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - autopep8
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.0
    - jsonschema >=3.2.0
    - jupyter_core >=4.0,<5.0
    - jupyter_client >=6.1
    - jupyterlab >=2.0.0,<3.0.0
    - jupyterlab-git ==0.23.1
    - kfp ==1.1.2
    - kfp-notebook >=0.17.0,<0.18.0
    - minio >=5.0.7,<7.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1,<6.0
    - nbdime >=2.0.0
    - nbresuse >=0.3.6
    - notebook >=6.0.3
    - papermill >=2.1.3
    - python >=3.6
    - requests >=2.9.1,<3.0
    - rfc3986-validator >=0.1.1
    - traitlets >=4.3.2
    - urllib3 >=1.24.2
    - websocket-client

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  dev_url: https://github.com/elyra-ai/elyra
  doc_url: https://elyra.readthedocs.io/en/latest
  doc_source_url: https://github.com/elyra-ai/elyra/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: Elyra, a set of AI-centric extensions for JupyterLab Notebooks.
  description: >
    Elyra currently includes: Notebook Pipelines visual editor Ability to run a notebook as a batch job Hybrid runtime support Python script execution capabilities within the editor Reusable Code Snippets (Experimental) Notebook versioning based on git integration Notebook navigation using auto-generated Table of Contents
    Reusable configuration for runtimes

extra:
  recipe-maintainers:
    - akchinSTC
    - kevin-bates
    - lresende
