{% set name = "elyra" %}
{% set version = "3.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-{{ version }}.tar.gz
  sha256: 27dc2d3bf256349c4519c87a0bd98eb2636db8e73b38fc8bb5461a1cd188aeec

build:
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
    - elyra-pipeline = elyra.cli.pipeline_app:pipeline
    - jupyter-elyra = elyra.elyra_app:launch_instance
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - autopep8 >=1.5.0
    - black >=22.8.0
    - click >=8
    - colorama
    - deprecation
    - entrypoints >=0.3
    - jinja2 >=3
    - jsonschema >=3.2.0,<4.0
    - jupyter_client >=6.1.7
    - jupyter_core >=4.11.2
    - jupyter_events <0.5.0
    - jupyter-packaging >=0.10
    - jupyter-resource-usage >=0.5.1
    - jupyter_server >=1.7.0
    - jupyterlab-git >=0.32,<1.0
    - jupyterlab-lsp >=3.8.0
    - jupyterlab >=3.4.6,<4.0
    - kfp >=1.7.0,<2.0,!=1.7.2
    - markupsafe >=2.1
    - minio >=7.0.0
    - nbclient >=0.5.1
    - nbconvert >=6.5.1
    - nbdime >=3.1,<4.0
    - nbformat >=5.1.2
    - networkx >=2.5.1
    - papermill >=2.3.4
    - pygithub
    - python-lsp-server >=1.1.0
    - pyyaml >=5.3.1,<6.0
    - requests >=2.25.1
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - typing-extensions >=3.10,<5
    - urllib3 >=1.26.5
    - watchdog >=2.1.3
    - websocket-client
    - yaspin

test:
  imports:
    - elyra
# conda compatibility for jupyter_core and python 3.7 https://github.com/elyra-ai/elyra/issues/3069
# Wait for pypi build >3.14.1 with https://github.com/elyra-ai/elyra/pull/3071
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  dev_url: https://github.com/elyra-ai/elyra
  doc_url: https://elyra.readthedocs.io/en/latest
  doc_source_url: https://github.com/elyra-ai/elyra/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: Elyra, a set of AI-centric extensions for JupyterLab Notebooks.
  description: >
    Elyra currently includes: Notebook Pipelines visual editor Ability to run a notebook as a batch job Hybrid runtime support Python script execution capabilities within the editor Reusable Code Snippets (Experimental) Notebook versioning based on git integration Notebook navigation using auto-generated Table of Contents
    Reusable configuration for runtimes

extra:
  recipe-maintainers:
    - akchinSTC
    - kevin-bates
    - lresende
