{% set name = "elyra" %}
{% set version = "2.1.0" %}
{% set sha256 = "6d3704fbbe581952864f5563c7f5a9272830391d7501f4371199a2f43b674850" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - elyra-metadata=elyra.metadata.metadata_app:MetadataApp.main

requirements:
  host:
    - pip
    - python
  run:
    - autopep8
    - black
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.0
    - jsonschema >=3.2.0
    - jupyter-resource-usage >=0.5.1
    - jupyter_client >=6.1.7
    - jupyter_core >=4.0,<5.0
    - jupyter_server >=1.2.0
    - jupyterlab >=3.0.0
    - jupyterlab-git ==0.30.0b1
    - jupyterlab-lsp >=3.0.0
    - kfp ==1.3.0
    - kfp-notebook ~=0.20.0
    - kfp-tekton ==0.6.0
    - minio >=5.0.7,<7.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1,<6.0
    - nbdime >=3.0.0.b1
    - nbformat >=5.1.2
    - papermill >=2.1.3
    - pygithub
    - python
    - python-language-server >=0.36.2
    - pyyaml >=5.3.1,<6.0
    - requests >=2.9.1,<3.0
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - urllib3 >=1.24.2
    - websocket-client

test:
  imports:
    - elyra
    - elyra.api
  commands:
    - pip check
    - elyra-metadata --help
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  dev_url: https://github.com/elyra-ai/elyra
  doc_url: https://elyra.readthedocs.io/en/latest
  doc_source_url: https://github.com/elyra-ai/elyra/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: Elyra, a set of AI-centric extensions for JupyterLab Notebooks.
  description: >
    Elyra currently includes: Notebook Pipelines visual editor Ability to run a notebook as a batch job Hybrid runtime support Python script execution capabilities within the editor Reusable Code Snippets (Experimental) Notebook versioning based on git integration Notebook navigation using auto-generated Table of Contents
    Reusable configuration for runtimes

extra:
  recipe-maintainers:
    - akchinSTC
    - kevin-bates
    - lresende
